### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by dee-y** [dsarlo/MusicRemote#1]
Hello, i am a graphic designer and i love contributing to opensource. I noticed your project readme doesn't have a logo yet. I would love to contribute a logo to this project for free. That is if you don't mind.

**Comment by dsarlo** [comment]
Of course you can! Go for it! That would be awesome. Let me know when you're done and I'll add it!

**Comment by dee-y** [comment]
Hi, I came with this design, with various fonts...do you like the logo? Is there a font you prefer?

![musicremote-01](https://user-images.githubusercontent.com/36637989/43691283-3ca5976e-9912-11e8-9e44-d670250a6fd8.png)

**Comment by dsarlo** [comment]
@dee-y I love 4, however, the slight separation you see on the left side throws me off a bit. Where the note makes contact with the top of the design

**Comment by dee-y** [comment]
oh owk...will fix that in a bit so you can re-access

**Comment by dee-y** [comment]
Hi @dsarlo what about now? any other adjustments? if none, what sizes/versions of logo will you need for final export...will also send editable SVG image along

![musicremote-01](https://user-images.githubusercontent.com/36637989/44038422-a9f81844-9f0e-11e8-9bda-4877e7fe0030.png)

**Comment by dsarlo** [comment]
Awesome! Love it! Honestly, not a logo expert, but I'll take the highest quality possible and shrink it down to whatever I need. Looks great!

**Comment by dee-y** [comment]
Hello, i have made a pull request here https://github.com/dsarlo/MusicRemote/pull/2
